# Generated by Django 2.1 on 2018-08-15 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publishe_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 23, 45, 57, 33230)),
            preserve_default=False,
        ),
    ]
