# Generated by Django 2.1 on 2018-08-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_publication_publishe_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='publishe_at',
            new_name='publish_at',
        ),
    ]
