language: python
python:
  - 3.6
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install Pipenv
  - pipenv install

script:
  - pipenv install --dev
  - pipenv run python manage.py migrate
  #- pipenv run pytest --cov=instagram -vv
